#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo-dark.png"
logo_footer = "images/logo-light.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "158px"
logo_height = "37px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "spydea"
# navbar fixed to top
navbar_fixed = true
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "" # contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
theme_copyright = true
copyright = "Copyright by your company"

# Preloader
[preloader]
enable = false
preloader = "images/logo-dark.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Integration"
link = "integration/"

[navigation_button_outline]
enable = true
label = "Get Started"
link = "contact/"

# contact info
[contact_info]
mobile = "+94746-388817"
email = "hello@spydea.com"

# Subscription
[announcement]
enable = true
content = "Pellen tesque in ipsum id orci porta dapibus. Sed port titor lectus nibh Vivamus [Learn More](#)"

# Subscription
[quote_form]
enable = true
submit_button_label = "Get A Quote"
placeholder = ""
action = "#"                        # contact form works with [https://airform.io/] , [https://formspree.io]

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# Valine Comment
[valine_comment]
enable = false
appId = ""     # replace this code with yours [ex: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI]
appKey = ""    # replace this code with yours [ex: WBmoGyJtbqUswvfLh6L8iEBr]
# language = "change language translation from `i18n`"
avatar = ""      # see : https://valine.js.org/en/avatar.html
pageSize = 10    # will show 10 comments per page
visitor = true
highlight = true # Code highlighting
recordIP = true  # Record reviewer IP.
enableQQ = false # https://valine.js.org/en/configuration.html#enableQQ
# serverURLs = "" # https://leancloud.your_website.com
# Check Valine's official documentation here - https://valine.js.org/en/configuration.html

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"]
description = "This is meta description"
author = "Themefisher"
image = "images/favicon.png"                                       # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "mastodon"
icon = "fab fa-mastodon" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
